name: Build iOS via Appflow

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  appflow_ios_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Appflow CLI
      run: |
        curl -fsSL https://ionic.io/get-appflow-cli | bash

    - name: Appflow iOS build
      run: |
        export IONIC_TOKEN=${{ secrets.IONIC_TOKEN }}
        appflow build ios development \
          --app-id ${{ secrets.APPFLOW_APP_ID }} \
          --commit=$(git rev-parse HEAD) \
          --ipa \
          --ipa-name="appflow_build_${{ github.run_number }}.ipa"

    - name: Download build artifact
      run: |
        export IONIC_TOKEN=${{ secrets.IONIC_TOKEN }}
        appflow build download-artifact \
          --app-id ${{ secrets.APPFLOW_APP_ID }} \
          --build-id $(appflow build list-builds --app-id ${{ secrets.APPFLOW_APP_ID }} --json | jq -r '.[0].buildId') \
          --artifact=IPA \
          --output ./appflow.ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Appflow IPA
        path: ./appflow.ipa